dist: trusty
sudo: required
language: cpp

before_install:
    - sudo apt-add-repository -y ppa:wpilib/toolchain
    - sudo apt-get update

install:
    - sudo apt-get install -y frc-toolchain
    - git clone https://github.com/intimitrons4604/tools-ci-cpp-build-script.git ~/tools-ci-cpp-build-script

script:
    - cd ~/tools-ci-cpp-build-script
    - ./gradlew --info -PsrcDir=$TRAVIS_BUILD_DIR/src clean build
