dist: trusty
sudo: required
language: cpp

before_install:
    - sudo apt-add-repository -y ppa:wpilib/toolchain
    - sudo apt-get update
    - git clone https://usfirst.collab.net/gerrit/p/allwpilib.git ~/allwpilib

install:
    - sudo apt-get install -y frc-toolchain protobuf-compiler libprotobuf-dev python3 clang-format-3.8
    - cd ~/allwpilib
    - ./gradlew tasks --all
#    - ./gradlew build -PmakeSim
    - ./gradlew :wpilibc:cmake
    - ls -alR build
