dist: trusty
sudo: required
language: java

before_install:
    - sudo apt-add-repository -y ppa:wpilib/toolchain
    - sudo apt-get update
    - git clone https://usfirst.collab.net/gerrit/p/allwpilib.git ~/allwpilib

install:
    - sudo sh -c 'echo \"deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main\" > /etc/apt/sources.list.d/gazebo-stable.list'
    - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
    - sudo apt-get install -y frc-toolchain libgazebo7-dev protobuf-compiler libprotobuf-dev python3 clang-format-3.8
    - cd ~/allwpilib
#    - ./gradlew tasks --all
    - ./gradlew build -PmakeSim
#    - ./gradlew :wpilibc:cmake
    - ls -alR build
