before_install:
    - sudo apt-add-repository -y ppa:wpilib/toolchain
    - sudo apt-get update
    - git clone https://usfirst.collab.net/gerrit/p/allwpilib.git ~/allwpilib

install:
    - sudo apt-get install -y frc-toolchain
    - ~/allwpilib/gradlew/:wpilibc:build