dist: trusty
sudo: required
language: java

before_install:
    - sudo apt-add-repository -y ppa:wpilib/toolchain
    - sudo apt-get update
    - git clone https://usfirst.collab.net/gerrit/p/allwpilib.git ~/allwpilib

install:
#    - sudo sh -c 'echo \"deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main\" > /etc/apt/sources.list.d/gazebo-stable.list'
#    - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
    - sudo apt-get install -y frc-toolchain protobuf-compiler libprotobuf-dev
    - cd ~/allwpilib
#    - ./gradlew tasks --all
    - ./gradlew build --debug
#    - ./gradlew :wpilibc:cmake
    - ls -alR build
